apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  annotations:
     description: "multi container pod with different commands testing"
  labels:
     type: multi-container-pod-type
spec:
  nodeName: node01
  containers:
    - name: container-one
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "ls; sleep 3600"]
    - name: container-two
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo Hello World; sleep 3600"]
    - name: container-three
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo this is the third container; sleep 3600"]