apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-poc
  annotations:
    description: "creating multi-container-pod which access emptydir on different paths"
  labels:
    type: pod-with-emptydir-type
spec:
  volumes:
    - name: empty-dir
      emptyDir: {}
  containers:
    - name: maincontainer
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5; done"]
      volumeMounts:
        - name: empty-dir
          mountPath: /var/log
    - name: sidecarcontainer
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: empty-dir
          mountPath: /usr/share/nginx/html
      